name: "Jenkins"
description: "Jenkins CI/CD"
version: "1.0.0"
slug: "jenkins"
init: false
arch:
  - aarch64
  - amd64
startup: services
ingress: true
ingress_stream: true
init: false
panel_icon: mdi:chart-timeline
panel_title: Ingress